{
 "title": "BankMore Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Response Time (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job=\"conta-corrente-api\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"conta-corrente-api\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"conta-corrente-api\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}