apiVersion: v1
kind: Service
metadata:
  name: tarifas-service
  namespace: bankmore
  labels:
    app: bankmore
    component: tarifas
spec:
  selector:
    app: bankmore
    component: tarifas
  ports:
  - name: http
    port: 5011
    targetPort: 5011
    protocol: TCP
  type: ClusterIP
