apiVersion: v1
kind: Service
metadata:
  name: transferencias-service
  namespace: bankmore
  labels:
    app: bankmore
    component: transferencias
spec:
  selector:
    app: bankmore
    component: transferencias
  ports:
  - name: http
    port: 5010
    targetPort: 5010
    protocol: TCP
  type: ClusterIP
